### **1. 넘파이 배열 생성**
##### numpy의 특징(숫자와 관련된 데이터의 연산을 빠르게 수행)

In [ ]:
import numpy as np

# 리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
arr = np.array(list1)  # 동일한 자료형을 배열로 변환
print("arr.shape", arr.shape)
print('arr type()', type(arr))
print(arr.dtype)

print('arr[0]', arr[0])
print('arr[1]', arr[1])
print('arr[2]', arr[2])
print('arr[3]', arr[3])


arr.shape (4,)
arr type() <class 'numpy.ndarray'>
int64
arr[0] 1
arr[1] 2
arr[2] 3
arr[3] 4


In [15]:
# 2차원 배열 생성하기

# import numpy as np

arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])  # tupple의 형태로 데이터를 반환, 생성된 행렬의 shape은 고정이 됨(2행 3열)
print("arr2.shape", arr2.shape)
print('arr2 type()', type(arr2))  # ndarray(numpy array)
print(arr2.dtype)   

print('arr2[0, 0]', arr2[0, 0])
print('arr2[0, 1]', arr2[0, 1])
print('arr2[0, 2]', arr2[0, 2])                                                                                                                                                     
print()
print('arr2[1, 0]', arr2[1, 0])
print('arr2[1, 1]', arr2[1, 1])
print('arr2[1, 2]', arr2[1, 2])


arr2.shape (2, 3)
arr2 type() <class 'numpy.ndarray'>
int64
arr2[0, 0] 1
arr2[0, 1] 2
arr2[0, 2] 3

arr2[1, 0] 4
arr2[1, 1] 5
arr2[1, 2] 6


In [ ]:
a = np.zeros(3)
print('a\t', a)

b = np.zeros((2, 2))
print('b\t', b)

c = np.ones((2, 3))
print('c\t', c)

d = np.full((2, 3), 5)
print('d\t', d)

e = np.eye(3) # 단위행렬
print('e\t', e)


a	 [0. 0. 0.]
b	 [[0. 0.]
 [0. 0.]]
c	 [[1. 1. 1.]
 [1. 1. 1.]]
d	 [[5 5 5]
 [5 5 5]]
e	 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# 실수형 배열 생성하기
# 1.
a = np.array([1, 2], dtype=np.float64)  # 할당한 64비트의 크기를 가진 메모리의 크기
print(a.dtype, a)

# 2.
b = np.array([1.5, 3.14])
print(b.dtype, b)

# 정수형 배열로 변환하기
a_i8 = a.astype(np.int8) # 1 byte로 정수값을 표현
print(a_i8.dtype, a_i8)
 

float64 [1. 2.]
float64 [1.5  3.14]
int8 [1 2]


In [96]:
# 1차원의 배열 생성하기
a = np.arange(8)  # vector로 데이터가 생성, 연속적으로 수치형의 데이터를 발생시키는 함수
print('a\n', a)
print('a.shape =', a.shape)

# 다차원 배열로 변경하기
a.shape = (2, 4) # 2행 4열의 형태로 shape을 변경 : 배열의 처음 값을 가지고 있음, 배열의 모양을 변경할 때는 .reshape()함수를 사용(Numpy 2.5부터)
# arr_re = a.reshape(2, 4) 
print('shape\n', a)

# 1차원 배열로 변경하기
print('flatten\n', a.flatten()) 

# resize 함수로 모양 변경
a.resize((4, 2))  # tupple의 형태
print('resize\n', a)



a
 [0 1 2 3 4 5 6 7]
a.shape = (8,)
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


C:\Users\admin\AppData\Local\Temp\ipykernel_22964\4140033222.py:7: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (2, 4) # 2행 4열의 형태로 shape을 변경 : 배열의 처음 값을 가지고 있음, 배열의 모양을 변경할 때는 .reshape()함수를 사용(Numpy 2.5부터)


In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]]) 
print('a\n', a) # 별도의 , 없이 출력

b = a.transpose() # 2 * 3 열의 데이터가 첫 요소가 한 묶음이 되서 3 * 2열로 변환(행열의 shape을 열행의 shape로 변환)
print('b\n', b)

c = a.T  # transpose()와 동일한 결과
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


In [46]:
# 3차원(Array, Tensor) 배열의 정의 -  2면 3행 4열 생성

array3 = np.array([ 
                    [ [1, 2, 3, 4],  # 1면
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12]], 
                    [ [21, 22, 23, 24], # 2면 
                    [25, 26, 27, 28], 
                    [29, 30, 31, 32]]
                 ])
print('arry3\n', array3)                
print('array3 type:', type(array3))
print('array3 array.shape', array3.shape)

print('array3 차원:', array3.ndim)  # n dimension


arry3
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]
array3 type: <class 'numpy.ndarray'>
array3 array.shape (2, 3, 4)
array3 차원: 3


In [54]:
# ndarray의 차원과 크기를 변경하는 reshape()

array10 = np.arange(10)
print(array10)

array11 = array10.reshape(2, 5)  # 2행5열로 변경 지정된 size만큼만 reshape 할 수 있음(arange(10))
print(array11)

array12 = array10.reshape(5, 2)
print(array12)

# array10.reshape(4, 3) # 12개의 데이터 지정된 size만큼만 reshape 할 수 있음(arange(10))


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array10 = np.arange(10)
print(array10)

array13 = array10.reshape(-1, 5) # 음수값으로 세팅되면 가변의 값이라는 의미,  5개의 열 값을 가지고 행의 갯수는 가변, 열을 기준으로 데이터 갯수만큼 자동으로 지정
print(array13)
print('array13 shape:', array13.shape)


array14 = array10.reshape(5, -1) # 음수값으로 세팅되면 가변의 값이라는 의미,  5개의 행 값을 가지고 행의 갯수는 가변, 행을 기준으로 데이터 갯수만큼 열을 자동으로 지정
print(array14)
print('array14 shape:', array14.shape)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array13 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array14 shape: (5, 2)


In [ ]:
array20 = np.arange(10)
print(array20.reshape(-1, 4)) # 열의 갯수는 4개씩 구성, 10개 데이터를 가지고 고정된 행값을 구할 수 없음, reshape() 변경 불가

In [ ]:
# n dimentional arry(ndarray)
array30 = np.arange(8)
array3d = array30.reshape((2, 2, 2)) # tupple형태로 선언 arange(8)
# print(array30)
print('array3d:\n', array3d)
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 nbarray로 변환
array5 = array3d.reshape(-1, 1)  # 열만 고정
print('array5:\n', array5.tolist())
print('array5 shape:\n', array5.shape)


# 1차원의 nbarray를 2차원 nbarray로 변환
array6 = array30.reshape(-1, 1)  # 열만 고정
print('array6:\n', array6.tolist())
print('array6 shape:\n', array6.shape)


array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:
 (8, 1)


* **Numpy에서 제공하는 np.sum함수의 axis의 이해**

In [ ]:
arr = np.arange(0, 24)
print(len(arr))
print(arr)




24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [88]:
v = arr.reshape([2, 3, 4]) # 3차원
print('v\n', v)

# print(v.shape)
# print(v.ndim) # 차원 출력

print('sum\n', v.sum())
res1 = v.sum(axis = 0) # z축(axis=0) : depth(면)을 기준으로 덧셈을 함, 행과 열만 남게됨
print('z축(axis=0)\n', res1)  # [0+12, 1+13, 2+14, 3+15], [4+16, 5+17, 6+18, 7+19], [8+20, 9+21, 10+22, 11+23]
print(res1.shape)

print()
res2 = v.sum(axis = 1) # x축(axis=1) : row(행)을 기준으로 덧셈을 함
print('x축(axis=1)\n',res2)  # [2, 3, 4] 3차원 배열을 2행4열로 반환  [0+4+8, 1+5+9, 2+6+10, 3+7+11], [15+19+23]
print(res2.shape)



v
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
sum
 276
z축(axis=0)
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)

x축(axis=1)
 [[12 15 18 21]
 [48 51 54 57]]
(2, 4)


In [ ]:
# x축 기준
res2 = v.sum(axis = 1) # x축(axis=1) : row(행)을 기준으로 덧셈을 함
print('x축(axis=1)\n',res2)
print(res2.shape)

x축(axis=1)
 [[12 15 18 21]
 [48 51 54 57]]
(2, 4)


In [ ]:
# y축 기준
res3 = v.sum(axis = 2) # y축(axis=2) : colum(열)을 기준으로 덧셈을 함
print('y축(axis=2)\n',res3)  # [0+1+2+3, 4+5+6+7, 8+9+10+11], 
print(res3.shape)

y축(axis=2)
 [[ 6 22 38]
 [54 70 86]]
(2, 3)


## **2.배열 원소 조회 및 정렬**

In [ ]:
mask = np.array([0, 1, 1, 0], dtype=bool)
mask1 = np.array([0, 10, 3.14, 0], dtype=bool) # 자동 형변환을 수행하면서 자료형을 통일
mask2 = np.array([0, 1 , 2, "홍길동"]) # 숫자형 문자열로 내부 자동 형변환

print(mask)
print(mask1)
print(mask2)

[False  True  True False]
[False  True  True False]
['0' '1' '2' '홍길동']


In [100]:
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)

data = np.random.randn(4, 2)  # 규칙적이지 않는 값을 배열의 자료형으로 값을 리턴 randn(random normal : 정규분포표 평균을 0로 표준편차를 1으로) 4 * 2 행렬
print('\ndata 출력\n ', data)


[False  True  True False]

data 출력
  [[-0.10409226  1.73359943]
 [ 0.9383787  -0.1983712 ]
 [-0.54379478 -1.46246978]
 [-0.74155807 -0.50990508]]


In [ ]:
# 데이터 접근을 인덱싱의 방법으로 mask변수에 담긴 값으로 접근, [False  True  True False] 으로 셋팅된 해당 위치의 값을 가져옴(True의 값 1, 2 항목만을 선택)
# 원하는 위치의 값만을 가져올 수 있음

print('\n 마스킹된 데이터 출력\n', data[mask]) 
print('\n 마스킹 역전된 데이터 출력\n', data[~mask])  # 틸트(~) 는 not의 의미 0, 4번째 값이 역전(True)되어 인덱스가 선택 



 마스킹된 데이터 출력
 [[ 0.9383787  -0.1983712 ]
 [-0.54379478 -1.46246978]]

 마스킹 역전된 데이터 출력
 [[-0.10409226  1.73359943]
 [-0.74155807 -0.50990508]]


In [110]:
posit = data[data > 0] # 비교연산을 통해서 인덱싱 값이 > 0 결과값을 True, False로 반환
print('\n양수 데이터 출력\n', posit)

# 다중 조건 
over1 = data[1][data[1] > 0] # 1행 양수인 값
print('\n두번째 행의 양수 데이터 출력\n', over1)

print('\n data 출력\n ', data)



양수 데이터 출력
 [1.73359943 0.9383787 ]

두번째 행의 양수 데이터 출력
 [0.9383787]

 data 출력
  [[-0.10409226  1.73359943]
 [ 0.9383787  -0.1983712 ]
 [-0.54379478 -1.46246978]
 [-0.74155807 -0.50990508]]


In [ ]:
# 배열의 인덱싱과 슬라이싱

arr = np.arange(16)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# 기본 인덱스
print(arr[15]) # 개별 데이터 값

15


In [ ]:
# 마이너스 인덱스  
print(arr[-1]) # 음수값은 뒤에서 부터 카운팅

15


In [ ]:
# 슬라이싱(인덱스 범위) 
print(arr[5:8]) # 일정 범위의 값(시작위치:끝위치(선언된 값 8직전까지의 데이터 5, 6, 7 반환))

[5 6 7]


In [126]:
# 값 할당(수정)
arr[5] = 100
arr


array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [ ]:
# 여러 값 할당
arr[6:8] = [200, 201] # 6, 7 두개의 데이터를 수정
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [128]:
# 다차원 배열
arr2 = np.arange(16).reshape(4, 4) # 메서드 체인 : 연속적으로 함수를 호출(.을 통해서 함수를 연결), 4행4열로 형태를 변경
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 개별 데이터 접근
print(arr2[1][1])  # 2번째 행, 2번째 열(개별 데이터 접근)
print(arr2[2])  # 3번째 행(특정 행)


5
[ 8  9 10 11]


In [ ]:
print(arr2[1, 2])  # print(arr2[1][2])와 동일
print(arr2[1][2])

6
6


In [135]:
arr2[1, 2] = 100
arr2

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [136]:
arr2[1:2] # 슬라이싱(범위) 1번 인덱스 

array([[  4,   5, 100,   7]])

In [ ]:
arr2[:2] # 처음부터 직전 까지의 모든 데이터 arr2[0:2]와 동일(0번, 1번 인덱스의 데이터) 

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7]])

In [138]:
arr2[2:]  # arr2[2:4]와 동일 2, 3 행의 데이터

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr2[0:2, 2:4] # 0, 1의 행부터 2, 3의 열 


array([[  2,   3],
       [100,   7]])

##### - 정수 배열을 사용하여 원하는 인덱스의 값을 지정(put)하거나 가져올 수(take) 있음

In [143]:
arr = np.arange(10)
index = [5, 3, 2, 6]

# index에 있는 값을 반환
arr.take(index)

array([5, 3, 2, 6])

In [145]:
# index에 있는 값을 치환
arr.put(index, 100)
arr

array([  0,   1, 100, 100,   4, 100, 100,   7,   8,   9])

In [ ]:
# index에 있는 값을 지정한 값(리스트)
arr.put(index, [50, 51, 52, 53])  # 5, 3, 2, 6 인덱스의 값을 지정한 값으로 변경
arr

array([ 0,  1, 52, 51,  4, 50, 53,  7,  8,  9])

### **3. 연산**

In [ ]:
# 리스트 연산
# list_data = [1, 2, 3, 4]
list_data = [1, 2, True, "홍길동", ["red", "green"]]
print(list_data * 2) # 리스트 사칙연산이 불가, list는 상이한 자료형을 선언이 가능

# numpy는?


[1, 2, True, '홍길동', ['red', 'green'], 1, 2, True, '홍길동', ['red', 'green']]


In [148]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [165]:
arr - 2
arr * 2
arr / 2


array([0.5, 1. , 1.5, 2. ])

In [ ]:
arr1 = np.array([1, 2, True, "홍길동", ["red", "green"]]) # error 동일한 자료형이 아니라 기준이 모호함, 배열로 변환이 안됨
arr1



In [173]:
arr = np.arange(5, 6, 7, 8)
arr

TypeError: Cannot interpret '8' as a data type

In [166]:
# 브로드캐스팅
# 원 데이터의 갯수와 연산을 수행해야 될 데이터 갯수가 일치하지 않을때 : 피연산자의 갯수만큼 내부적으로 더 만들어서 동일한 값으로 채운뒤 개별적으로 연산이 수행되게 함
np.arange(3) + 2   # 0 2, 1 2, 2 2

array([2, 3, 4])

In [171]:
np.ones((3, 3))  # 3*3열



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [172]:
np.ones((3, 3))  + np.arange(3) # 브로드캐스팅 arange(3) 0,1,2를 채워서 연산

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

##### - 주요 산술 연산 함수

In [174]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [175]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16])

In [ ]:
# 제곱근(루트) 
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [177]:
# exp(지수승)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [178]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [180]:
# add
np.add(arr, 23)

array([24, 25, 26, 27])

In [181]:
# subtract
np.subtract(arr, 1)

array([0, 1, 2, 3])

In [184]:
# multiply
np.multiply(arr, 4)

array([ 4,  8, 12, 16])

In [185]:
# divide
np.divide(arr, 2)

array([0.5, 1. , 1.5, 2. ])

In [187]:
# float divide
np.floor_divide(arr, 0.25)

array([ 4.,  8., 12., 16.])

In [ ]:
# mod
np.mod(arr, 4) # 두 배열 원소 나눗셈의 정수 나머지 반환

array([1, 2, 3, 0])

In [191]:
# sum
print('합계', np.sum(arr))
print('평균', np.mean(arr))

합계 10
평균 2.5


In [ ]:
# axis를 인자로 받아 차원에 따른 연산 수행
arr_multi = np.arange(16).reshape(4,4)
print(arr_multi)

print('mean of axis 0 :', arr_multi.mean()) # 나누기 16
print('mean of axis 0 :', arr_multi.mean(axis=0))  # 2차원배열(0,1의 값이 존재) : axis=0은 행단위로 개별적으로 계산 0+4+8+12/4 = 6, 1+5+9+13/4 = 7, 
print('mean of axis 1 :', arr_multi.mean(axis=1))  # 2차원배열(0,1의 값이 존재) : axis=1은 열단위로 개별적으로 계산 4+5+6+7/4 = 1.5

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
mean of axis 0 : 7.5
mean of axis 0 : [6. 7. 8. 9.]
mean of axis 1 : [ 1.5  5.5  9.5 13.5]


In [ ]:
print(arr)
# 편차
print(np.var(arr))

# 표준편차
print(np.std(arr))

# 최소값
print(np.min(arr))

# 최대값
print(np.max(arr))

# 최소값의 인덱스 반환
print('argmin 인덱스:', np.argmin(arr))

# 최대값의 인덱스
print('argmax 인덱스:', np.argmax(arr))


[1 2 3 4]
1.25
1.118033988749895
1
4
argmin 인덱스: 0
argmax 인덱스: 3


In [ ]:
# 행렬 곱 (2행3열 데이터, 3행2열의 데이터를 곱셈)
x = np.arange(6).reshape(2, 3)  # 0 ~ 5 
y = np.arange(6).reshape(3, 2) 
print('x \n', x)
print('y \n', y)

print('\nx.dot(y)\n ', x.dot(y))  # 행열의 계산
print('\nx.dot(y)\n', np.dot(x, y))
# 0*0+1*2+2*4 = 10
# 0*1+1*3+2*5 = 13
# 3*0+4*2+5*4 = 28
# 3*1+4*3+5*5 = 40

x 
 [[0 1 2]
 [3 4 5]]
y 
 [[0 1]
 [2 3]
 [4 5]]

x.dot(y)
  [[10 13]
 [28 40]]


##### - 기타 연산
        - where : 조건절

In [210]:
arr = np.arange(10).reshape(2, 5)
print("arr\n", arr)

# arr의 원소가 5보다 크면 10, 그렇지 않을 경우 0으로 반환
np.where(arr > 5, 10, 0)

arr
 [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ 0,  0,  0,  0,  0],
       [ 0, 10, 10, 10, 10]])

### - sort : 정렬

In [ ]:
arr = np.random.randn(5)  # rand normal(randn : 표준 정규분포를 따르는 데이터 셋에서 랜덤하게 5개 값을 꺼내옴)
print('정렬 이전 :', arr)

arr.sort() #오름차순 정렬  행단위로 정렬
print('정렬 이후 :', arr)



정렬 이전 : [-0.31777315  0.43368494  0.4372937  -0.48094575  0.99624915]
정렬 이후 : [-0.48094575 -0.31777315  0.43368494  0.4372937   0.99624915]


In [ ]:
arr = np.random.randn(9).reshape(3, 3)  # rand normal(randn : 표준 정규분포를 따르는 데이터 셋에서 랜덤하게 9개 값을 꺼내와서 2차원 배열로 reshape)
print('\n정렬 이전\n :', arr)

arr.sort(axis=0)  # x축을 기준으로 정렬(2차원 배열에서 axis=0은 x축 즉 행단위)
print('\n정렬 이후(axis=0)\n :', arr)



정렬 이전
 : [[-1.10951447 -1.06387777 -0.45216118]
 [ 1.1153493   0.40505026  1.37767872]
 [-1.29194908  0.13531613  1.25633077]]

정렬 이후(axis=0)
 : [[-1.29194908 -1.06387777 -0.45216118]
 [-1.10951447  0.13531613  1.25633077]
 [ 1.1153493   0.40505026  1.37767872]]


In [2]:
import numpy as np
arr = np.random.randn(9).reshape(3, 3)  # rand normal(randn : 표준 정규분포를 따르는 데이터 셋에서 랜덤하게 9개 값을 꺼내와서 2차원 배열로 reshape)
print('\n정렬 이전\n :', arr)

arr.sort(axis=1)  # y축을 기준으로 정렬(2차원 배열에서 axis=1은 y축 즉 열단위)
print('\n정렬 이후(axis=1)\n :', arr)



정렬 이전
 : [[ 1.25978114  0.25650406  1.4543102 ]
 [-1.10470454  0.74821661  1.48754155]
 [-1.30603752  1.32994801 -0.36728644]]

정렬 이후(axis=1)
 : [[ 0.25650406  1.25978114  1.4543102 ]
 [-1.10470454  0.74821661  1.48754155]
 [-1.30603752 -0.36728644  1.32994801]]
