### hihell -> ihello : hihello
- Hi Hello RNN

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
idx2char = ['h', 'i', 'e', 'l', 'o']

num_classes = 5
input_dim = 5
sequence_length = 6  # hihell
learning_rate = 0.1

In [4]:
# x_data = [[0, 1, 0, 2, 4, 4]] # hihell
y_data = [[1, 0, 2, 3, 3, 4]]   # ihello  정답 데이터

# onehot encoding으로 전처리
x_one_hot = np.array([[[1,0,0,0,0], # 'h' 첫번째 인덱스 위치
                       [0,1,0,0,0], # 'i' 두번째 인덱스 위치
                       [1,0,0,0,0], # 'h' 첫번째 인덱스 위치
                       [0,0,1,0,0], # 'e' 세번째 인덱스 위치
                       [0,0,0,1,0], # 'l' 네번째 인덱스 위치
                       [0,0,0,1,0]]],# 'l'
                     dtype=np.float32)
                     
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes) # to_categorical() 정수값으로 담겨진 데이터를 자동으로 onehot encoding방식으로 펼쳐줌

In [5]:
print(x_one_hot.shape) # 학습
print(y_one_hot.shape) # 정답 

# 1, 6, 5  : 입력 6, 5개의 feature 특징, 3차원
# 정답 데이터도 동일(onhot encoding방식)

(1, 6, 5)
(1, 6, 5)


In [ ]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(sequence_length, input_dim)),  # 입력 레이어
    tf.keras.layers.RNN(
        cell=tf.keras.layers.LSTMCell(units=num_classes),  # 5번 반복
        return_sequences=True
    )
])

In [7]:
# 완전 연결형 레이어(fully connected layer)를 추가적으로 붙여줌
# TimeDistributed() 시간의 순차적 데이터를 처리

model.add(tf.keras.layers.TimeDistributed( \
    tf.keras.layers.Dense(units=num_classes, activation='softmax')))

In [ ]:
# Adam 알고리즘 적용

model.compile(loss='categorical_crossentropy',
   optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
             metrics=['accuracy'])

In [9]:
model.fit(x_one_hot, y_one_hot, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1667 - loss: 1.5867   
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 1.4575
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3333 - loss: 1.3504
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3333 - loss: 1.2341
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3333 - loss: 1.0953
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.9380
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8333 - loss: 0.7835
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.6476
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5316
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4296
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.3439
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.2833


In [10]:
predictions = model.predict(x_one_hot) # 알파벳 'o'가 예측 되어야 함

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step


In [11]:
# 알파벳 'o'가 예측됨
for i, prediction in enumerate(predictions):
    print(prediction)
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print('\t예측 결과: ', ''.join(result_str))

[[5.7398924e-05 9.9922192e-01 6.8636454e-04 3.3111493e-05 1.1858281e-06]
 [9.9740273e-01 2.5981519e-04 2.2723649e-03 2.5641519e-05 3.9391631e-05]
 [1.2698580e-03 1.3995125e-03 9.9688834e-01 4.4230191e-04 5.6411025e-08]
 [1.8648299e-05 3.5682222e-06 1.0754920e-03 9.9889970e-01 2.5112549e-06]
 [2.7955940e-04 9.9648321e-07 3.5238201e-05 9.9818307e-01 1.5011400e-03]
 [9.6361694e-04 6.4814626e-06 2.1485938e-08 1.5507941e-03 9.9747914e-01]]
	예측 결과:  ihello
